services:
  backend:
    build: be
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=tablereservation
    networks:
      - spring-postgres
    stdin_open: true
    tty: true
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=tablereservation
      - POSTGRES_PASSWORD=prova
    expose:
      - 5432
volumes:
  db-data:
secrets:
  db-password:
    file: .env
networks:
  spring-postgres:
